### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mirzadeh** [mayhl/gadit#2]
Hey,

I saw your entry in the gallery of fluid motion. I'm trying to build your code but it looks like one of the files is missing from the repository?

`fatal error: work_space.h: No such file or directory`

Thanks

**Comment by mirzadeh** [comment]
Amazing work by the way 👍  :)

**Comment by mayhl** [comment]
Hi - Thank you. Sorry there are still a few issues with the code. I unfortunately develop the code on Windows,  and have been having trouble with my Ubuntu boot, see read me file for more info. 

This compile errors, however, seems to be an unexpected error. Sorry if this is a dumb question, but did I upload the work_space.h file? Looking at my log file it seems I may have not.

Also which platform are you trying to compile this code on.

You may also want to try downloading the slightly revised version. I will polishing off GADIT and will be updating GitHub for the next few weeks.
